sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: XS971818

  alioss:
    bucket-name: xs-sky-itcast
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key- id: LTAI5t6FhmN4ZPgbt8UXdqar
    access-key-secret: 3vRd8HxBUY6ngn6f2IiPHeGTvbpmv1

  Redis:
      host: localhost
      port: 6379
      password: XS971818
      database: 0