sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: XS971818

  alioss:
    bucket-name: xs-sky-itcast
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key- id: LTAI5t6FhmN4ZPgbt8UXdqar
    access-key-secret: 3vRd8HxBUY6ngn6f2IiPHeGTvbpmv1

  Redis:
      host: localhost
      port: 6379
      password: XS971818
      database: 0

  wechat:
    appid: wxfd2e70d12fed690f
    secret: 1a4410dc1c3fefb3016ac69b56a2f3db
    #    mchid: //商户号
    #    mchSerialN0: //商户证书序列号
    #    apiV3Key: //APIV3密钥
    #    notifyUrl: //回调地址
    #    privateKeyFilePath: //私钥文件路径
    #    weChatPayCertFilePath: //微信支付平台证书文件路径
    #    refundNotifyUrl: //退款回调地址
  baidu:
    # 百度地图AK，需要在百度地图开放平台申请
    ak: eieLcGL6Ggf9BCAFiYlvqOUKGCXaebCY
    # 商家门店地址
    shop-address: 湖北省武汉市武昌区
